# Generated by Django 5.2.7 on 2025-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='car_name',
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
